core:
  registry: docker.io
  tag: 5.3.2
  psp: false
  rbac: true # required for rancher authentication
  serviceAccount: default

  global:
    controller:
      tag: 5.2.4
      image: controller
      registry: docker.io/neuvector
    manager:
      tag: 5.2.4
      image: manager
      registry: docker.io/neuvector
    enforcer:
      tag: 5.2.4
      image: enforcer
      registry: docker.io/neuvector


  controller:
    # If false, controller will not be installed
    enabled: true
    image:
      repository: neuvector/controller
    replicas: 3

    pvc:
      enabled: true
      accessModes:
        - ReadWriteMany
      storageClass: "longhorn"
      capacity: 5Gi

  manager:
    enabled: true
    image:
      repository: neuvector/manager
    env:
      ssl: true
      envs: []

    type: ClusterIP # should be set to - ClusterIP

    ingress:
      enabled: true
      host: neuvector.labjoel.com
      ingressClassName: "traefik"
      path: "/"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls: true
      secretName: neuvector-tls
