kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-configmap
data:
  known_devices.yaml: |
  automations.yaml: |
  configuration.yaml: |-
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
    influxdb:
      api_version: 2
      ssl: true
      host: hassinfluxdb.labjoel.com
      port: 443
      token: influxdb-token
      organization: influxdata
      bucket: default
      tags:
        source: HA
      tags_attributes:
        - friendly_name
      default_measurement: units
