kube-prometheus-stack:
  ## Deploy alertmanager
  alertmanager:
    enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts: ["alertmanager.labjoel.com"]
      tls: 
      - secretName: alertmanager-general-tls
        hosts:
        - alertmanager.labjoel.com

    # Setup persistent HA storage
    alertmanagerSpec:
      storage:
       volumeClaimTemplate:
         spec:
           storageClassName: longhorn
           accessModes: ["ReadWriteMany"]
           resources:
             requests:
               storage: 5Gi


  ## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  grafana:
    grafana.ini:
        auth:
            signout_redirect_url: "https://authentik.labjoel.com/application/o/grafana/end-session/"
            oauth_auto_login: true
        auth.generic_oauth:
            name: authentik
            enabled: true
            client_id: h7FFUqMBN7oU4ZsI6drVkJmN2Erjxb3MD1g7pcz4
            client_secret: $__file{/etc/secrets/auth_generic_oauth/client_id}
            scopes: "openid profile email"
            auth_url: "https://authentik.labjoel.com/application/o/authorize/"
            token_url: "https://authentik.labjoel.com/application/o/token/"
            api_url: "https://authentik.labjoel.com/application/o/userinfo/"
            role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
        server:
          root_url: "https://grafana.labjoel.com"
    enabled: true

    extraSecretMounts:
      - name: auth-generic-oauth-secret-mount
        secretName: auth-generic-oauth-secret
        defaultMode: 0440
        mountPath: /etc/secrets/auth_generic_oauth
        readOnly: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts: ["grafana.labjoel.com"]
      tls: 
      - secretName: grafana-general-tls
        hosts:
        - grafana.labjoel.com

    # Setup persistent HA storage
    persistence:
      enabled: true
      type: pvc
      storageClassName: longhorn
      accessModes:
        - ReadWriteMany
      size: 5Gi
      finalizers:
        - kubernetes.io/pvc-protection

  ## Deploy a Prometheus instance
  prometheus:
    enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth-to-authentik@kubernetescrd
      hosts: ["prometheus.labjoel.com"]
      tls: 
      - secretName: prometheus-general-tls
        hosts:
        - prometheus.labjoel.com

    # Setup persistent HA storage
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 15Gi
