- hosts: all
  tasks:
  - name : Install packages required to use longhorn
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    loop:
      - open-iscsi
      - nfs-common
    become: true
