apiVersion: v2
name: teslamate
version: 0.0.0
dependencies:
  - name: app-template
    version: 3.1.0
    repository: https://bjw-s.github.io/helm-charts/
  - name: postgresql
    version: "15.5.1"
    repository: https://charts.bitnami.com/bitnami
