app-template:

  controllers:
    main:
      # -- enable the controller.
      enabled: true
      # -- Set the controller type.
      # Valid options are deployment, daemonset or statefulset
      type: deployment
      # -- Set annotations on the deployment/statefulset/daemonset
      annotations: {}
      # -- Set labels on the deployment/statefulset/daemonset
      labels: {}
      # -- Number of desired pods
      replicas: 1
      revisionHistoryLimit: 3

      containers:
        main:
          image:
            repository: teslamate/teslamate
            tag: 1.28.5

          # -- environment variables. See [teslamate docs](https://docs.teslamate.org/docs/configuration/environment_variables) for more details.
          env:
            # -- Set the container timezone
            TZ: America/Chicago
            DISABLE_MQTT: true
            DATABASE_HOST: teslamate-postgresql.teslamate.svc.cluster.local
            DATABASE_NAME: teslamate
            DATABASE_USER: postgres
            POSTGRES_DB: teslamate

          envFrom:
            - secretRef:
                name: teslamate-secret
          probes:
            liveness:
              enabled: true
              custom: false
              type: TCP
              spec:
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness:
              enabled: true
              custom: false
              type: TCP
              spec:
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            startup:
              enabled: true
              custom: false
              type: TCP
              spec:
                initialDelaySeconds: 0
                timeoutSeconds: 1
                periodSeconds: 5
                failureThreshold: 30

    grafana:
      # -- enable the controller.
      enabled: true
      # -- Set the controller type.
      # Valid options are deployment, daemonset or statefulset
      type: deployment
      # -- Set annotations on the deployment/statefulset/daemonset
      annotations: {}
      # -- Set labels on the deployment/statefulset/daemonset
      labels: {}
      # -- Number of desired pods
      replicas: 1
      revisionHistoryLimit: 3

      containers:
        main:
          image:
            repository: teslamate/grafana
            tag: 1.28.5

          # -- environment variables. See [teslamate docs](https://docs.teslamate.org/docs/configuration/environment_variables) for more details.
          env:
            # -- Set the container timezone
            TZ: America/Chicago
            DATABASE_HOST: teslamate-postgresql.teslamate.svc.cluster.local
            DATABASE_USER: teslamate
            DATABASE_NAME: teslamate
            DATABASE_PASS:
              valueFrom:
                secretKeyRef:
                  name: teslamate-secret
                  key: DATABASE_PASS

          probes:
            liveness:
              enabled: true
              custom: false
              type: TCP
              spec:
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness:
              enabled: true
              custom: false
              type: TCP
              spec:
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            startup:
              enabled: true
              custom: false
              type: TCP
              spec:
                initialDelaySeconds: 0
                timeoutSeconds: 1
                periodSeconds: 5
                failureThreshold: 30
  service:
    main:
      enabled: true
      type: ClusterIP
      controller: main
      ports:
        http:
          port: 4000
    grafana:
      enabled: true
      type: ClusterIP
      controller: grafana
      ports:
        http:
          port: 3000

    # -- Enable and configure ingress settings for the chart under this key.
  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host teslamate.labjoel.com
          paths:
            - path: /
              service:
                identifier: main
      tls:
        - hosts:
            - *host
          secretName: teslamate-tls
    grafana:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth-to-authentik@kubernetescrd
      hosts:
        - host: *host
          paths:
            - path: /
              service:
                identifier: grafana
      tls:
        - hosts:
            - *host
          secretName: teslamatedash-tls

  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteMany
      size: 15Gi
      storageClass: longhorn

postgresql:
  auth:
    # grabs the user password from the telsamate-secret
    existingSecret: teslamate-secret
    username: teslamate
    database: teslamate
    secretKeys:
      adminPasswordKey: DATABASE_PASS
      userPasswordKey: DATABASE_PASS
  primary:
    persistence:
      enabled: true
      size: 15Gi
      storageClass: longhorn
