app-template:
  controllers:
    cloudflared:
      containers:
        app:
          image:
            repository: docker.io/cloudflare/cloudflared
            tag: 2024.6.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
  configMaps:
    config:
      enabled: true
      data:
        config.yaml: |
          tunnel: homelab
          credentials-file: /etc/cloudflared/credentials.json
          metrics: 0.0.0.0:2000
          no-autoupdate: true
          ingress:
            - hostname: '*.labjoel.com'
              service: https://traefik.kube-system.svc.cluster.local
              originRequest:
                noTLSVerify: true
            - service: http_status:404
  persistence:
    config:
      enabled: true
      type: configMap
      name: cloudflared-config
      globalMounts:
        - path: /etc/cloudflared/config.yaml
          subPath: config.yaml
    credentials:
      enabled: true
      type: secret
      name: cloudflared-credentials
      globalMounts:
        - path: /etc/cloudflared/credentials.json
          subPath: credentials.json
