longhorn:
  preUpgradeChecker:
    # -- Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
    jobEnabled: false
    # -- Setting that allows Longhorn to perform upgrade version checks after starting the Longhorn Manager DaemonSet Pods. Disabling this setting also disables `preUpgradeChecker.jobEnabled`. Longhorn recommends keeping this setting enabled.
    upgradeVersionCheck: true
  ingress:
    # -- Setting that allows Longhorn to generate ingress records for the Longhorn UI service.
    enabled: true

    # -- IngressClass resource that contains ingress configuration, including the name of the Ingress controller.
    # ingressClassName can replace the kubernetes.io/ingress.class annotation used in earlier Kubernetes releases.
    ingressClassName: traefik

    # -- Hostname of the Layer 7 load balancer.
    host: longhorn.labjoel.com

    # -- Setting that allows you to enable TLS on ingress records.
    tls: true

    # -- Setting that allows you to enable secure connections to the Longhorn UI service via port 443.
    secureBackends: true

    ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
    # -- Ingress annotations in the form of key-value pairs.
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
