---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgBECClI33o+5qH7qTB+HmlHlQspoiVNK7+y5miRdR801WR07S6OGG6IyXGm1marr16RSn+yHAVeF/uqmEmgXVUIhaGa5fNif0VTKs3edsNOgNGjc/Jut0n8GFhxB4gHFgqx3ETRzpGQnLSVGs7GfBzj/QBdSqAP5bdg6YTOq052f/8KOk9rH4UfCCfO9Z5BQ84+3Y4GXcCWev6hkmsnNZi9kB+3p5yUxUmRWH4P/89cXp7ZLSlBTYu58WeLnUWGQ8DCfaeYNJcnVc4tNcGmpvBgq0IYUWJRaZrSO24QwuXMdI08k1nQqz06mrZauct5MLhhc2av32rLRGgWzMd7W5mgBZVhcYoefdr8hzIRWPjHXuHET5WjSvMat6v/u5m5Tj5q5D4LYjCD8fkR8RXGLy94OIkRDzHyOO2xN/+gZdD/LNlL64Ry+DN70P87b5qCagwJXny9amhdY/ntfUJ/D2WyXI6cgVm/4x3gtotrm4bx+TjqFVBNyiQh857NDfL6Ar7Up59a3hFnwN8nt2RoBKqjpzs8oXuJwCJS98Nfwqbz3d3FK/u2zXWV/o5TxY930XqO2wSYPuINt7YuM84IPpBHZNEQR/a5lOjO15681oh8neszLzKZkCaFHGGBM70fNQPGPA+f5YBga333K7Rj3aKNe07UhXAt9LGOwt4ym9CLZ+BDtWxpZSxVdma9RdI2i94VZJp/Z5llwX3m2qir9CVQwXbQIJbRubhjFqWixHqf2ghcTtYteCO9ySGNhrsRIhudgw==
    AUTHENTIK_SECRET_KEY: AgA6WuihsBmlt7DY7v9EjQvzqUojdVjZG69yynfibf/lewE7i6GVoTOywNRTBaLjMlWn6lP6XBUaXoMOt59dWhCgBXg/rLTl6FT7g7IRnHAO9wmf3T5VQr/jJIFtyW5usC3IMk+Z3/CGaGfcrmMuF+jh5R3v/JO/gHK/sSOAuUlweGcuJ8lHj7+5AgzlS40jCFoTi15CIBYEXhf3HSR0RwIdg+8kKizpXDsCkbVNBFV4b+3X7hVTZCSqpt+cyHSihHW1CqzfDJadtGea0TT1pTwsx/9VAx53hnCkGRNkTSK0hS3yIMYwGhg8VvAC5cJV9BTbH71p0GOZCOP+xBhiZe24Q/i3UGlrViYD+GFu7Ph7F1/wmtijqpJLsPZf9r5VWmQHlYXRhJKTkuyl3WgcEAg322GKPnmWJQZhJc/roJUG5zqUtfxiCFa0LXtf1djX4sJ3ydlq1zsgLZPbpGQV7ztsb19l31eZhEwvoyqgw4C0KlxkDH7T9ZnNv8IGh4j/0SiL/mB+gLHiRqTobLPYzPdHuStZ5iyfsId+gzstBlzXpR2WNd8vqDehqFnt3FSBts852XlrrrMNVbTrz7BEOuizW1jSPRQXG8tdEz4Iul4GpuHNy816o9hUxT44xZxGPF5OR+r2MzKYk+11q05EvvlhkRhXWhNEmVrOdYaf/o57LnUS8rDd2/LVVcC7LrvrIlHfdIMqbJx1PXEbYJ8TiyE5q1U8evtr9grrQ7JCqZP0Ii06zlKxFUflDkn6rc3GoOZVYA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
