---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: authentik
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCkD23DA1Q7b6FH0704gU2fU8i7oPNlXgpM+QwURO+imWj0w2lvMEiyORLCxnVai7tHyiBp3Qpa5xdLnIF0Pc6eyq5HXbADLCw2k8FlcoHpaQcNaX39SYO7mgD2Kpr9JhIOnrL1WWAsfasdsrtcUecnRXT87PHUgKEUB/jHyISkNcTosckn27zdfkCpinRVVl+mhHSolCxW/Bki1mJeyHuQ5hUmCFgHxcr7I7kAkK1t1ZOcxC5jYMciSWd1gE/FYs/CTB7ZqiyU3CyGx8+LXzM1HxGO2VUfK2vHajCUwjwg2ciaAw7FXnuh3tYWeUlnrJW2UMs3TVo4YGtYxWMIYJqiSBs3a6Kw2pRDedir85wNTgorKBXSwUOlm+LoFKWjxLH4GY7DJxQ84aIKmWphWHDPCcjZBaFSUdRRsi2ScskeEIyDCse3N9HrUvlUhP36d4xVGZKm90LjDe5wdp8DQMV/G99wuK++Jp2bXqhSizEkb8RuLLca8bGBJpHXpVzf2lqs/fX1hVd8+Rfotcg+TglJhXGlFcnvGvNgikZ910CEde4w1p43M06JXt34GcBwgIyWOBmUBEANgDYQqk240fbauK3fpk+CqovbZFkES8gjUXnMTs9fvmybJRNvGnXtC4tohR5tNtVKs8eWpfPIOwJCcZDN0WJnAHyKqV5y6JJm8ctKsspBrUHnZ6Pu1xVXTYo7lHytX5Qfj8iSlQMz21XOg8DNOE/bPVHkqXOgF8cSbMZiy9BPDRA2W98S8gVuH9D7Zg==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: authentik
