kratos:
  replicaCount: 1
  image:
    repository: oryd/kratos
    tag: v1.1.0
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  ## -- Service definitions
  service:
    admin:
      enabled: true
      metricsPath: /admin/metrics/prometheus
    public:
      enabled: true

  ## -- Secret management
  secret:
    # -- switch to false to prevent creating the secret
    enabled: true
    # -- Provide custom name of existing secret, or custom name of secret to be created
    nameOverride: ""

  ## -- Ingress definition
  ingress:
    admin:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: kratos.admin.labjoel.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: kratos-admin-tls
          hosts:
            - kratos.admin.labjoel.com
    public:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: kratos.public.labjoel.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: kratos-public-tls
          hosts:
            - kratos.public.labjoel.com

  ## -- Application specific config
  kratos:
    development: false
    # -- Enable the initialization job. Required to work with a DB

    # -- Enables database migration
    automigration:
      enabled: true

    # -- You can add multiple identity schemas here. You can pass JSON schema using `--set-file` Helm CLI argument.
    identitySchemas: {}
    # identitySchemas:
    #  "identity.default.schema.json": |
    #    {
    #      // ...
    #    }
    #  "identity.email.schema.json": |
    #    {
    #      // ...
    #    }
    #  "identity.phone.schema.json": |
    #    {{ .Values.phone_schema }}

    # -- You can customize the emails Kratos is sending (also uncomment config.courier.template_override_path below)
    emailTemplates: {}
    # emailTemplates:
    #   recovery:
    #     valid:
    #       subject: Recover access to your account
    #       body: |-
    #         Hi, please recover access to your account by clicking the following link:
    #         <a href="{{ .RecoveryURL }}">{{ .RecoveryURL }}</a>
    #       plainBody: |-
    #         Hi, please recover access to your account by clicking the following link: {{ .RecoveryURL }}
    #     invalid:
    #       subject: Account access attempted
    #       body: |-
    #         Hi, you (or someone else) entered this email address when trying to recover access to an account.
    #         However, this email address is not on our database of registered users and therefore the attempt has failed. If this was you, check if you signed up using a different address. If this was not you, please ignore this email.
    #       plainBody: |-
    #         Hi, you (or someone else) entered this email address when trying to recover access to an account.
    #   verification:
    #     valid:
    #       subject: Please verify your email address
    #       body: |-
    #         Hi, please verify your account by clicking the following link:
    #         <a href="{{ .VerificationURL }}">{{ .VerificationURL }}</a>
    #       plainBody: |-
    #         Hi, please verify your account by clicking the following link: {{ .VerificationURL }}
    #     invalid:
    #       subject:
    #       body:
    #       plainBody:

    config:
      secrets: {}

  ## -- Parameters for the Prometheus ServiceMonitor objects.
  # Reference: https://docs.openshift.com/container-platform/4.6/rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.html
  serviceMonitor:
    # -- switch to true to enable creating the ServiceMonitor
    enabled: true
    # -- HTTP scheme to use for scraping.
    scheme: http
    # -- Interval at which metrics should be scraped
    scrapeInterval: 60s
    # -- Timeout after which the scrape is ended
    scrapeTimeout: 30s
    # -- Provide additional labels to the ServiceMonitor ressource metadata
    labels: {}
    # -- TLS configuration to use when scraping the endpoint
    tlsConfig: {}

