---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCQ+kFw0JbivKr/Sp6OcX404PAZdF0phHGRNZ7PVQPU960KMiRV+A+lBVIf7jNVrB0+Z9Bq/1OWXYENmybiJeQtI1SamJMiButZKUTEpHZQUxMOYKOXhqpflzzehkj0ST5t2K+qJQDHqpPGLdyzToJwwzOe/kNgokaDEcus+o28VWgKATmFnJaGujqvBm6MPSPyXX1wfSbxlQkiGid1SpqvH/G8TIFlvWRT3wXYurN7maN4Tagz1WAIX9+sRjvsl2kSxfMG3oSLEpQcwLRMYlvGjKZssfIdjIKwjpH59aN2qajYEVPkoCAjhpSHPGs5OCQg1pqQKDdQLP/nmrb0Rv0viEYQRXxzN9khbKzC+KQRQU92OQPPyWP4mlzpy1NDNNV68Ec3Q9Fe9YjsBQxR8tkpElfHGBzwVNUF5YLjnf8rR0GSugtU27VB4zJkBTxdWMjBIh5dZLZRG0SVYjoKU9i4TwRvbeyD7bWNVGlprnv1IKMV/O+DxSIgpVXO0dU5J+7MysfuR+UPoHom/N0BcrVuKjKI7uucN64zjYG2nLus82sZkxRA7kALR0vKWJZwGh6meCkNw4XDbNNe1toNomVQKvjfB6H7nc93IxVH2hFRsihDaHesefnfHrWemBV3xHc93nq2joGpLX9FfVqhHHTr+/KNeB2kfsyIrwHYQ9awGFXxblcR77ayXuLE8yeACq0oJzmP7m/oiIxZPyhd0PAXjTSCzfhP+9M254ztNYLZZnl1fyGa3T6jmPl9vr03PSF7ffPGnIxjIG8ivBnOTzJgpjPRjX0wharDQAD3vz49Xq9AT767MNmKEztSbHFbpLGMJ6ecpF/gbyMhoE4XAHp/JdmBGe6BKVMh1iX/7Xm50urIM6ArpdSbpwOeUVm94tpBqGT6IeiEohEru26l54NQig==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflared
