home-assistant:
  replicaCount: 1
  # Environment variables
  env: 
    - name: TZ
      value: America/Chicago

  # Specifies if the containers should be started in hostNetwork mode.
  # Required for use auto-discovery feature of Home Assistant
  hostNetwork: true

  # Ingress settings
  ingress:
    # Enable ingress for home assistant
    enabled: true
    className: ""
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    hosts:
      - host: homeassistant.labjoel.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
     - secretName: chart-homeassistant-tls
       hosts:
         - homeassistant.labjoel.com

  # Persistence values for the Home Assistant instance
  persistence:
    # Enable or disable persistence
    enabled: true
    # Access mode for the persistent volume claim
    accessMode: ReadWriteMany
    # Size of the persistent volume claim
    size: 5Gi
    # Storage class for the persistent volume claim
    storageClass: "longhorn"

