---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-generic-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgAvBqOO7Fi1zpP3EgjgMzd1gMG2BFMhyzLHE8XRhJjDJ2ANcn1NEHdIycFRR4sD7/QW449HtjN0amhuPPrDjZvewSqxXYg4LiJgdeP6rlXVWdj+f0wqFp3vJXBrW/wpJtdcqaB8q2BKjB4yw3gyt7jtx5i2bMj0NPgfphWo5y/0M43Hxv0Pe0zlJL2PIXTOAHPW/j+v9qdoXhEOqSeWJiOCwunC6ImGRKXXBbbVTYYAHuzbolH7GbwCWHjcYKXbDS7U4XCOOHMfD3AQzRyg3w88pT83gCDAI+g7wmonJhJ49aHmPxdp2nbOPe8oKj4MyqJ8Yz7UsSBZxTTlegelgfiMDWfCI2CE1snHOBX2UrjEnsO4R6UEu6Axh+ioDgo3u/iAcsChSkHujlffWco+b+dc12iFkrHSUm/uABcnL4/IpYGOqZPthSD9ePTrOxpvehWH9DR/cVSxonR2K5MxlUsCu5HoH5PQwFpU/RU9WrzXy4RnBbv6Vpt8sjhmBj3Fzg/dSyI0IO0JfX6V3nLPFCdW6LLJSpHorb1lYouqE26mIJsHQ3x31v92kYMH8YYOxtEwdyuVPKs3+eaBgacGHnishVTlMvCGhZ/fcMVww8v/wnLTPZdg4se8Wi4LzUA8yJSordGFQgr+15RPHPFFQg1NQcDDnXKlCFf0G3SKG9dRkFbv3aiWHuIJJYXjO2nT9qGByIisgrrxOmozjSnOyy05HTSKGCWyXnkjly0iafxLbVx6qPvPlSNDVPz/VGie3SIT4T7FPDYvd16t3P3V8+t3bKHwkLj5Sorsa86q4MbOTlJs0HZgqHVQouc25jb5DxWa8G1Z0J8hopt5IRKhQdf94sMam3rY9TA7bEg/TBsNRQ==
  template:
    metadata:
      creationTimestamp: null
      name: auth-generic-oauth-secret
      namespace: monitoring
