---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kratos-secret
  namespace: identity
  annotations:
      helm.sh/hook: pre-install, pre-upgrade
      helm.sh/hook-delete-policy: before-hook-creation
      helm.sh/hook-weight: "0"
      helm.sh/resource-policy: keep
spec:
  encryptedData:
    dsn: AgCqk8lFTJguKrZ+HO/2fLgC45f+gFSJxQ/TftJFxLcihyE6tAN9Oqra4Ya0DRnvTOjVO0zLx/ELTPwzLDqtaZp09lK1vuUOur07fG63RMkkioXU5tNTzOS9SftoQ2+YhWFNWqLFRzBH07/Bm4K5z7SHZDHsrvTqfRxlfdqI5j+R3+jOlX1bGdraDtZqJSF+8jE44jW9fy0unQ8m8fsLQ9u0lq/EnJVyeH11wyej5xstZC1Y3Tcbgnz83KIhqUthcOzn1dEVDsyaLaa7W5TqsEKRo/6Mr+TnLaObH9OsKZ1xSpgVCIQ1vA7TIhTbN6aRHeMJMuws35ytl+XvN0SDb7SlmHxDRhKwIcVon7AgeSLCiJYppa7aNWQVnlhj7s72ZGIp4TLTD92CwG9Mso57uQXu4E/tKSvt/nqkysCBXgpCnnaWKFjgovwhrSUw9/FszNhQ1M9fd0r3BafSfYZchjUbNS7NV5mQCjDV4D47TVAiwDAyAhzJrYNykQBe8DAM2LTIkZyADXoxUcxC8jxzJOnj27cw/pOz6Q+krNuuiIWuhPfG6LgMxmI8MmkhG5e3ODNwHzCG24DBp0l35Rvq1fE3Gsz568jugJlC5yKjrFyaiTydXzfKk6MoItXqzNHIN/P9HUGyHUWPbL9uDrTby9Kv3SOprTAt8A5IapItE+G3vNYs9CnC9GKOCM7OQ8offAckNgbb8UqGgqM21MRs7WjAy1Rycbr2KalVbuGV6GlwCZVN6F707koEWHGO3HidQbwU/rkSkubD11EAX4AsBfWx5ZG3j1tesQ+MrR75ivINUE13YgZKmPn0bbte293UsmIJPU6E92g9b7GscE+rPkXp
  template:
    metadata:
      creationTimestamp: null
      name: kratos-secret
      namespace: identity
