---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: identity
  annotations:
      helm.sh/hook: pre-install, pre-upgrade
      helm.sh/hook-delete-policy: before-hook-creation
      helm.sh/hook-weight: "0"
      helm.sh/resource-policy: keep
spec:
  encryptedData:
    DATABASE_PASS: AgAQbaDXViepRZbdTy1p354gsEMZ5/SSeOnZqQOuiLO3MjWzLmjOKLsmisgdsHNTZiSHj3tJLWKxkmd3bQxXW3/1mFOds7OtADCbjI9+I1H4xMTKV3ALZiAH01wVqezmcHVe5JAZ6XRJRlNgVNodEIpu8jytnNvwIlrKJIY72oQ648oxc+y85Rpa/C++zO+tIjc0p7HV1ekPFGSKtmF8ri01RK7U4N2tHe7PqkNA9i9VW27x939TA2pWEo2QMxA/UAqIQ/cFQU/xHP34ZAlvEcYL8xkaPC/mCx+dm2w/7mvEzNX3YMf5P+cV6FhexdOq+AC0+VxpUxN/q3c5mRSoEPByTbV6w14FMrFlomr3uInsIlj0ht8cj70tMXL7lvEMVQCUzDB6wsAZ1xT48Aw8bb2GU9yhR87XZB1soQEsBuNd3Fi41QRAGlF4mwpe6/UoH5vhRMeVLpI/5Y+OyvSVWXSmDjLIZnhJWtJ8z5sQNVr4vjxosgmnCGecYrCFvqE5fB2kr0NVhPOO+vYyHC4C8NgYkCG5XLfuPkNqRyJz1UYLmLCVCHM0HsdYnLRVSL1KlK41IgwSUXvjaOuy7u7mxKjuk+bV0Ajo8aadqKXuqaLAy5Gb/0Cfh8TAJpkjvgG0mcmpYIPD8l6zNx0eAwLbR6bQsm6j+ttytLM0lV6xaHcEH0fW/oEHFMPhKh7iPExsWVyctIPRD/q0EYw=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: identity
