argo-cd:
  global:
    domain: argocd.labjoel.com
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      tls: true
      # TODO: Enable this when prometheus is up
    metrics: &metrics
      enabled: false
      serviceMonitor:
        enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
argocd-apps:
  applicationsets:
    root:
      namespace: argocd
      generators:
        - git:
            repoURL: &repoURL https://github.com/joelmccoy/homelab.git
            revision: &revision main
            directories:
              - path: system/*
      template:
        metadata:
          name: '{{path.basename}}'
        spec:
          project: default
          destination:
            name: in-cluster
            namespace: '{{path.basename}}'
          source:
            repoURL: *repoURL
            targetRevision: *revision
            path: '{{path}}'
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            retry:
              limit: 10
              backoff:
                duration: 1m
                factor: 2
                maxDuration: 16m
            syncOptions:
              - CreateNamespace=true
              - ApplyOutOfSyncOnly=true
              - ServerSideApply=true
